import { API_BASE, handleResponse } from './common'


export interface Invoice {
    id: string
    unitId: string
    providerId: string
    invoiceNumber: string
    isAutogenerated?: boolean
    invoiceDate: string
    dueDate?: string
    subtotal: number
    taxIva: number
    totalAmount: number
    description?: string
    pdfUrl?: string
    fileUrl?: string
    status: string
    paidAmount?: number
    balance?: number
    monthlyReportId?: string
}

export async function getInvoices(filters?: { unitId?: string; providerId?: string; status?: string }): Promise<{ invoices: Invoice[] }> {
    const params = new URLSearchParams()
    if (filters?.unitId) params.set('unitId', filters.unitId)
    if (filters?.providerId) params.set('providerId', filters.providerId)
    if (filters?.status) params.set('status', filters.status)
    const res = await fetch(`${API_BASE}/invoices?${params}`)
    return handleResponse<{ invoices: Invoice[] }>(res, 'Error al obtener facturas')
}



export async function getInvoice(id: string): Promise<Invoice> {
    const res = await fetch(`${API_BASE}/invoices/${id}`)
    return handleResponse<Invoice>(res, 'Error al obtener factura')
}



export async function createInvoice(data: Partial<Invoice>): Promise<Invoice> {
    const res = await fetch(`${API_BASE}/invoices`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(data)
    })
    return handleResponse<Invoice>(res, 'Error al crear factura')
}



export async function updateInvoice(id: string, data: Partial<Invoice>): Promise<Invoice> {
    const res = await fetch(`${API_BASE}/invoices/${id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(data)
    })
    return handleResponse<Invoice>(res, 'Error al actualizar factura')
}



export async function deleteInvoice(id: string): Promise<{ success: boolean }> {
    const res = await fetch(`${API_BASE}/invoices/${id}`, { method: 'DELETE' })
    return handleResponse<{ success: boolean }>(res, 'Error al eliminar factura')
}



export async function getInvoiceStats(unitId?: string): Promise<any> {
    const url = unitId ? `${API_BASE}/invoices/stats/summary?unitId=${unitId}` : `${API_BASE}/invoices/stats/summary`
    const res = await fetch(url)
    return handleResponse<any>(res, 'Error al obtener estadísticas')
}



export async function getNextCCNumber(unitId: string): Promise<{ number: string; prefix: string; nextNumber: number }> {
    const res = await fetch(`${API_BASE}/invoices/next-cc-number?unitId=${unitId}`)
    return handleResponse(res, 'Error al obtener próximo número')
}

