import { API_BASE } from './common'

export interface Invoice {
    id: string
    unitId: string
    providerId: string
    invoiceNumber: string
    isAutogenerated?: boolean
    invoiceDate: string
    dueDate?: string
    subtotal: number
    taxIva: number
    totalAmount: number
    description?: string
    pdfUrl?: string
    fileUrl?: string
    status: string
    paidAmount?: number
    balance?: number
    monthlyReportId?: string
}

export async function getInvoices(filters?: { unitId?: string; providerId?: string; status?: string }) {
    const params = new URLSearchParams()
    if (filters?.unitId) params.set('unitId', filters.unitId)
    if (filters?.providerId) params.set('providerId', filters.providerId)
    if (filters?.status) params.set('status', filters.status)
    const res = await fetch(`${API_BASE}/invoices?${params}`)
    return res.json()
}

export async function getInvoice(id: string) {
    const res = await fetch(`${API_BASE}/invoices/${id}`)
    return res.json()
}

export async function createInvoice(data: Partial<Invoice>) {
    const res = await fetch(`${API_BASE}/invoices`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(data)
    })
    return res.json()
}

export async function updateInvoice(id: string, data: Partial<Invoice>) {
    const res = await fetch(`${API_BASE}/invoices/${id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(data)
    })
    return res.json()
}

export async function deleteInvoice(id: string) {
    const res = await fetch(`${API_BASE}/invoices/${id}`, { method: 'DELETE' })
    return res.json()
}

export async function getInvoiceStats(unitId?: string) {
    const url = unitId ? `${API_BASE}/invoices/stats/summary?unitId=${unitId}` : `${API_BASE}/invoices/stats/summary`
    const res = await fetch(url)
    return res.json()
}

export async function getNextCCNumber(unitId: string): Promise<{ number: string; prefix: string; nextNumber: number }> {
    const res = await fetch(`${API_BASE}/invoices/next-cc-number?unitId=${unitId}`)
    return res.json()
}
