import { z } from 'zod';

export const createInvoiceSchema = z.object({
    unitId: z.string().uuid("Unit ID inválido"),
    providerId: z.string().uuid("Provider ID inválido"),
    invoiceNumber: z.string().min(1, "El número de factura es requerido"),
    invoiceDate: z.coerce.date(),
    dueDate: z.coerce.date().optional(),
    subtotal: z.number().positive("El subtotal debe ser positivo"),
    taxIva: z.number().min(0).default(0),
    retefuenteAmount: z.number().min(0).default(0),
    reteicaAmount: z.number().min(0).default(0),
    totalAmount: z.number().positive("El total debe ser positivo"),
    description: z.string().optional(),
    fileUrl: z.string().url("URL de archivo inválida").optional().or(z.literal("")),
    pdfUrl: z.string().url("URL de PDF inválida").optional().or(z.literal("")),
    source: z.string().default("MANUAL"),
    status: z.enum(['PENDING', 'PAID', 'CANCELLED', 'DRAFT']).default('PENDING'),
    isAutogenerated: z.boolean().default(false).optional()
});

export const updateInvoiceSchema = createInvoiceSchema.partial();
